const { MAIN_VITE_OPENAI_API_KEY, MAIN_VITE_OPENAI_ORG_ID } = import.meta.env;

export const OPENAI_API_KEY = MAIN_VITE_OPENAI_API_KEY;
export const OPENAI_ORG_ID = MAIN_VITE_OPENAI_ORG_ID;

export const OPENAI_MODEL = 'gpt-4o-2024-11-20';
